# Generated by Django 5.0.2 on 2024-02-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myprofile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="age",
            field=models.IntegerField(default=18),
        ),
    ]
